name: Build

on: push

jobs:
  build:
    runs-on: macos-latest

    env:
      DEFAULT_PYTHON: 3.8
      PIPELINE_CONTEXT: DEV
      PIPELINE_LIBRARY_PATH: ${{ github.workspace }}/.github/library

    steps:

      # Checkout your source repo (must do this before the library)
      - name: Checkout source Git repo
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ci

